name: pipeline week 7-8

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ['master']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # bước 1: lấy thông tin
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Quan trọng: SonarQube cần cái này để phân tích lịch sử

    # bước 2: thiết lập môi trường python & node
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    # bước 3: SAST với semgrep
    - name: Install Semgrep
      run: pip install semgrep

    - name: Semgrep Scan
      run: semgrep scan --config auto --error
      env:
        MY_APP_SECRET_KEY: "${{ secrets.MY_APP_SECRET_KEY }}"

    # bước 4: SAST với SonarQube
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        args: >
          -Dsonar.projectKey=linhdieumai_VAmPI
          -Dsonar.organization=linhdieumai
          -Dsonar.exclusions=.github/**
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
    # bước 4.1: quality gate check của sonar
    - name: SonarQube Quality Gate Check
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    # bước 5: SCA với Snyk
    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Snyk SCA Test
      run: snyk test --severity-threshold=high
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
