name: pipeline week 7-8

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ['master']

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    # bước 1: lấy thông tin
    - uses: actions/checkout@v4

    # bước 2: thiết lập môi trường python & node
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    # bước 3: SAST với semgrep
    - name: Install Semgrep
      run: pip install semgrep

    - name: Semgrep Scan
      run: semgrep scan --config auto --error # Thêm --error để fail pipeline nếu có lỗi nặng
      env:
        MY_APP_SECRET_KEY: "${{ secrets.MY_APP_SECRET_KEY }}"
