name: Unit test tự động khi có pull request

on:
  pull_request:
    branches: ['main']

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    # bước 1: lấy thông tin
    - uses: actions/checkout@v4
    # bước 2: thiết lập môi trường python
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    # bước 3: cài đặt pytest
    - run: |
      python -m pip install --upgrade pip
      pip install pytest
    # bước 4: chạy unit test
    - name: chạy unit test 
      run: pytest
    